query Week($id: ID!) {
            week(id: $id){
              id
              beginDate
              endDate
              note
              communications {
                id
                type
                subject
                teacher{
                  firstname
                }
                body
                documents{
                  name
                }
            }
        }
}